// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xgphduleuvohrcxhejyn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhncGhkdWxldXZvaHJjeGhlanluIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg3NjAwODEsImV4cCI6MjA2NDMzNjA4MX0.vCUaox5l_qCJElY3rdBGGQwePERs1y_bzt0PyCiB1yc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);